### ISSUE TITLE
options_page has been deprecated. Use options_ui instead.

### ISSUE THREAD

**Issue by PauloBoks** [headzoo/ruqqus-plus#1]
It works fine on chrome but on firefox it's not supported and options_ui is supported by both.

[From firefox documentation](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/options_page)

I don't _want_ to open a pull request so here is the idea on how to fix:

change this: `"options_page": "html/settings.html"`

to this:
```
"options_ui": {
  "page": "html/settings.html",
  "open_in_tab": true
}
```

I am trying to get it working (natively) on firefox, doesn't seem that hard.

**Comment by headzoo** [comment]
Okay, I'll make the switch. I remember writing a couple of bits of code that had me thinking, "This won't work in Firefox." But I can't remember what they are now. Figured I'd cross that bridge later. Let me know if you make any progress. Thanks!

**Comment by headzoo** [comment]
FYI, I think I've got everything working in firefox now.

**Comment by PauloBoks** [comment]
hell yeah, i don't even know about extension i just google the error and tried fixing them, wouldn't get me very far lol

**Comment by headzoo** [comment]
The addon has been accepted by the Firefox store.

https://addons.mozilla.org/en-US/firefox/addon/ruqqus-plus/
