### ISSUE TITLE
User info is not cached

### ISSUE THREAD

**Issue by PauloBoks** [headzoo/ruqqus-plus#2]
Currently the user info when you hover over someones name is not cached so every time it fetch the data again causing it to fell slower than desirable.

My suggestion is just hide the "box" instead of deleting (removing) it as it does for now. Basically instead of this:
```
if (box) {
  box.forEach((b) => {
    b.remove();
  });
}
```
You could have something closer to this:
`box.hidden = true;`

Obviously as is you also would need to change more things in handleMouseEnter and getBoxTemplate, just trying to be helpful here.

**Comment by headzoo** [comment]
You're right. Just pushed changes to hide the box and then re-use it later on instead of fetching the user info again.
